### ISSUE TITLE
`juliaup` does not install/alias `julia` as expected by the `juliaup` README

### ISSUE THREAD

**Issue by jmuchovej** [conda-forge/juliaup-feedstock#32]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When installing `juliaup`, I have `juliaup` and `julialauncher` installed. From the video linked in #17, it seems that `julia` is actually an alias for `julialauncher`, but this isn't obvious from unless you watch that particular video.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by mkitti** [comment]
From the README at https://github.com/JuliaLang/juliaup/blob/main/README.md it seems the way to install is via a shell script rather than using `cargo --install`

```julia
curl -fsSL https://install.julialang.org | sh
```

**Comment by mkitti** [comment]
Here is a link the shell script in the repository.
https://github.com/JuliaLang/juliaup/blob/main/deploy/shellscript/juliaup-init.sh

Here's a larger question. If this package and the `julia-feedstock` are both installed, how do we deconflict the situation?

**Comment by jmuchovej** [comment]
This appears to be resolved, at least in more recent versions of the feedstock. (When I've installed `juliaup` from `conda-forge`, I correctly get a `julia` program (and `julialauncher` is nowhere to be found).

I'll leave it open until maintainers see this, but feel free to close, I think. 🙂

**Comment by mkitti** [comment]
Are you sure? I just checked and this has not changed.

**Comment by mkitti** [comment]
Also, I think the actual solution to this is to create an alternate install of the `julia` package that uses `juliaup` to install `julia`.
